"""
Django settings for GroceriesTracker project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.utils.csp import CSP
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY and os.getenv('DEBUG', 'False') == 'False':
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("The SECRET_KEY env var must be set in production.")
SECRET_KEY = SECRET_KEY or 'django-insecure-fallback-key-for-dev'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't', 'y', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'groceries.samuelpetre.com').split(',')
if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['']:
    ALLOWED_HOSTS = ['groceries.samuelpetre.com']

# Allow local development
ALLOWED_HOSTS += ['localhost', '127.0.0.1', '[::1]']

# Proxy / HTTPS hardening (Cloudflare Tunnel -> http://192.168.1.50:8000)
# Tunnel terminates TLS; Django must trust X-Forwarded-Proto for is_secure()/CSRF.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# CSRF + cookies for the public origin. Localhost stays usable for checks.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://groceries.samuelpetre.com',
    ).split(',') if o
]
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() in ('true', '1', 't', 'y', 'yes')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() in ('true', '1', 't', 'y', 'yes')
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # must stay readable by Django admin JS
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

# Force HTTPS for any request that arrives without X-Forwarded-Proto: https.
# Safe here: Cloudflare Tunnel always sends the header, and the healthcheck
# sends it explicitly so http://127.0.0.1:8000 checks stay redirect-free.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 't', 'y', 'yes')

# HSTS: 1 year. Env-overridable so you can relax it without editing code:
#   SECURE_HSTS_INCLUDE_SUBDOMAINS=False  -> only this host is pinned to HTTPS
# Note: every *.samuelpetre.com subdomain is published through Cloudflare as
# HTTPS-only, so includeSubDomains is safe here. SSH (ssh.samuelpetre.com) is
# unaffected: browsers only apply HSTS to HTTPS, never to ssh://.
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('true', '1', 't', 'y', 'yes')
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').lower() in ('true', '1', 't', 'y', 'yes')

# Application definition
# ... (existing APPS and MIDDLEWARE) ...

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'error.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'tracker': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'axes',
    'tracker',
]

Q_CLUSTER = {
    'name': 'GroceriesTrackerTasks',
    'workers': 1,
    'recycle': 500,
    'timeout': 120,
    'retry': 180,
    'save_limit': 500, # Increased to reduce frequent DELETE operations
    'label': 'Django Q',
    'orm': 'default',
}

# WhiteNoise: serve /static/ straight from gunicorn (no extra web server).
# Middleware order matters: SecurityMiddleware -> WhiteNoise -> rest.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_LOCKOUT_PARAMETERS = ['username']
AXES_IPWARE_META_PRECEDENCE_ORDER = ('REMOTE_ADDR',)
AXES_RESET_ON_SUCCESS = True
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False
AXES_HTTP_RESPONSE_CODE = 429
AXES_DISABLE_ACCESS_LOG = True
# Single-user app behind one Cloudflare Tunnel IP: lock on username only
# so X-Forwarded-For spoofing can't bypass or dilute the limit (W006 N/A).
SILENCED_SYSTEM_CHECKS = [
    'axes.W006',
]

SECURE_CSP = {}
SECURE_CSP_REPORT_ONLY = {
    'default-src': [CSP.SELF],
    'script-src': [CSP.SELF, 'https://cdn.jsdelivr.net'],
    'style-src': [CSP.SELF, 'https://fonts.googleapis.com'],
    'font-src': [CSP.SELF, 'https://fonts.gstatic.com'],
    'img-src': [CSP.SELF, 'data:', 'https:'],
    'connect-src': [CSP.SELF],
    'object-src': [CSP.NONE],
    'base-uri': [CSP.SELF],
    'form-action': [CSP.SELF],
    'frame-ancestors': [CSP.NONE],
}

ROOT_URLCONF = 'GroceriesTracker.urls'

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tracker.context_processors.admin_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'GroceriesTracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 60, # Extreme patience for SQLite locks
            'transaction_mode': 'IMMEDIATE',
            # WAL mode. HISTORY: with WAL + single-file bind mounts, each
            # container got private -wal/-shm sidecars -> split brain (worker
            # couldn't see web's writes). That is fixed: compose now mounts the
            # whole project dir, so the sidecar files are shared by all
            # processes and WAL is safe AND desirable here: readers (gunicorn)
            # never block the writer (qcluster) and vice versa.
            # busy_timeout (60s) serializes the remaining writer-vs-writer
            # collisions; note SQLite bypasses the busy handler on read->write
            # lock upgrades, which only matters in rollback-journal mode.
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA busy_timeout=60000;',
        }
    }
}

# Product enrichment (tracker/enrichment.py). Contact identifies our traffic
# to Open Food/Beauty Facts (required by their API terms); the Mercado Livre
# catalog token unlocks GTIN-verified catalog lookups (optional).
ENRICHMENT_CONTACT = os.getenv(
    'ENRICHMENT_CONTACT',
    'GroceriesTracker (+https://github.com/Finrood/GroceriesTracker)',
)
MELI_ACCESS_TOKEN = os.getenv('MELI_ACCESS_TOKEN', '')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'django_cache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Receipts are Brazilian wall-clock (America/Sao_Paulo); grouping by month /
# weekday must use local time, otherwise UTC shifts buckets near midnight.
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 4.2+ style storage config (replaces deprecated STATICFILES_STORAGE).
# CompressedManifestStaticFilesStorage = hashed names + gzip/brotli precompression,
# served by WhiteNoise straight from gunicorn.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (Uploaded product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# IPCA reference series (Banco Central SGS, monthly %).
# Food code is env-overridable and surfaced in the UI next to the label, so a
# wrong default stays visible instead of silently mislabeling the chart.
IPCA_SERIES = {
    'IPCA geral': int(os.getenv('IPCA_SERIES_GERAL', '433')),
    'IPCA alimentação': int(os.getenv('IPCA_FOOD_SERIES', '1635')),
}
