# Generated by Django 6.0.2 on 2026-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='normalized_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='cnpj_root',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
    ]
