# Generated by Django 6.0.2 on 2026-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_category_options_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='consumer_cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='series',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_federal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_municipal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_state',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
