# Generated by Django 6.0.2 on 2026-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_receipt_consumer_cpf_receipt_number_receipt_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
