# Generated by Django 6.0.2 on 2026-03-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_pricehistory_product_parent_store_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(db_index=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_mappings', to='tracker.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.store')),
            ],
            options={
                'unique_together': {('store', 'internal_code')},
            },
        ),
    ]
