# Generated by Django 6.0.2 on 2026-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_productmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
