# Generated by Django 6.0.2 on 2026-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_product_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
