# Generated by Django 6.0.2 on 2026-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_product_local_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
