# Generated by Django 6.0.2 on 2026-03-03 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_product_is_manually_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='tracker_pri_product_80863c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together={('user', 'store', 'internal_code')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['user', 'product', 'store', 'date'], name='tracker_pri_user_id_f0e990_idx'),
        ),
    ]
