# Generated by Django 6.0.2 on 2026-03-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_pricehistory_tracker_pri_product_80863c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
