# Generated by Django 6.0.2 on 2026-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_product_weight_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_enrichment_attempt',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
