# Generated by Django 6.0.2 on 2026-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_product_last_enrichment_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
