# Generated by Django 6.1.1 on 2026-09-15 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_productmapping_is_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='access_key',
            field=models.CharField(db_index=True, max_length=44),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('user', 'access_key'), name='uniq_receipt_user_accesskey'),
        ),
    ]
