# Generated by Django 6.1.1 on 2026-09-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_gtin_not_null',
        ),
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='ph_prod_store_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmapping',
            name='pm_store_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='receiptitem',
            name='ri_receipt_product_idx',
        ),
        migrations.AddField(
            model_name='canonicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_products', to='tracker.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tracker.canonicalproduct'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['canonical'], name='tracker_pro_canonic_01f83e_idx'),
        ),
        migrations.AddField(
            model_name='canonicalsuggestion',
            name='product_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_suggestions_a', to='tracker.product'),
        ),
        migrations.AddField(
            model_name='canonicalsuggestion',
            name='product_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_suggestions_b', to='tracker.product'),
        ),
        migrations.AddConstraint(
            model_name='canonicalsuggestion',
            constraint=models.UniqueConstraint(fields=('product_a', 'product_b'), name='uniq_canon_sugg_pair'),
        ),
    ]
